<!--异常信息头-->
【异常时间】：2020-01-02 14:45:20,888 [10] ;
【异常级别】：ERROR 
【抛出信息】：发生了未知内部错误 
【异常类型】：NullReferenceException 
【异常信息】：Object reference not set to an instance of an object. 
【堆栈调用】：   at WebApplication1.Controllers.HomeController.Index() in E:\CoreTest\WebApplication1\WebApplication1\Controllers\HomeController.cs:line 19
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync() 
 <!--异常信息尾部-->
<!--异常信息头-->
【异常时间】：2020-01-02 14:48:43,586 [15] ;
【异常级别】：ERROR 
【抛出信息】：发生了未知内部错误 
【异常类型】：NullReferenceException 
【异常信息】：Object reference not set to an instance of an object. 
【堆栈调用】：   at WebApplication1.Controllers.HomeController.Index() in E:\CoreTest\WebApplication1\WebApplication1\Controllers\HomeController.cs:line 19
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync() 
 <!--异常信息尾部-->
<!--异常信息头-->
【异常时间】：2020-01-02 15:08:49,946 [9] ;
【异常级别】：ERROR 
【抛出信息】：发生了未知内部错误 
【异常类型】：NullReferenceException 
【异常信息】：Object reference not set to an instance of an object. 
【堆栈调用】：   at DAL.EFTransactionBase.CommitTransaction() in E:\CoreTest\WebApplication1\DAL\EFTransactionBase.cs:line 49
   at WebApplication1.Controllers.HomeController.Index() in E:\CoreTest\WebApplication1\WebApplication1\Controllers\HomeController.cs:line 24
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync() 
 <!--异常信息尾部-->
<!--异常信息头-->
【异常时间】：2020-01-02 15:10:38,801 [8] ;
【异常级别】：ERROR 
【抛出信息】：发生了未知内部错误 
【异常类型】：NullReferenceException 
【异常信息】：Object reference not set to an instance of an object. 
【堆栈调用】：   at DAL.EFTransactionBase.CommitTransaction() in E:\CoreTest\WebApplication1\DAL\EFTransactionBase.cs:line 49
   at WebApplication1.Controllers.HomeController.Index() in E:\CoreTest\WebApplication1\WebApplication1\Controllers\HomeController.cs:line 24
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync() 
 <!--异常信息尾部-->
